services:
  eureka-service:
    image: eureka-service
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - spring-network

  config-service:
    image: config-service
    build:
      context: ./config-service
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/app/config-data
    volumes:
      - ./config-data:/app/config-data  # Mapea la carpeta local al contenedor
    ports:
      - "8081:8081"
    networks:
      - spring-network

  gateway-service:
    image: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
      - config-service
    networks:
      - spring-network

  carro-service:
    image: carro-service
    build:
      context: ./carro-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - eureka-service
    volumes:
      - ~/.m2:/root/.m2  # Solo en carro-service para el repositorio Maven local
    networks:
      - spring-network

  moto-service:
    image: moto-service
    build:
      context: ./moto-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - eureka-service
    volumes:
      - ~/.m2:/root/.m2  # Solo en moto-service para el repositorio Maven local
    networks:
      - spring-network

  usuario-service:
    image: usuario-service
    build:
      context: ./usuario-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - eureka-service
    networks:
      - spring-network

  auth-service:
    image: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-service
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

