server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/usuario/**
          filters:
            - AuthFilter
        - id: carro-service
          uri: lb://CARRO-SERVICE
          predicates:
            - Path=/carro/**
        - id: moto-service
          uri: lb://MOTO-SERVICE
          predicates:
            - Path=/moto/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
    
logging:
  level:
    org.springframework.cloud.gateway: DEBUG


     