server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: Docker
          uri: https://github.com/EliezerRojasP/microservicios-proyecto
          search-paths: config-data
  application:
    name: config-service